### ISSUE TITLE
cputop doesn't work with Python 3.10

### ISSUE THREAD

**Issue by AmarOk1412** [lttng/lttng-analyses#94]
```
docker@a6e0d2a2abac:~/ansible$ lttng-cputop result/hostdpdk/600/config_s8_60/
Traceback (most recent call last):
  File "/usr/local/bin/lttng-cputop", line 5, in <module>
    from lttnganalyses.cli.cputop import run
  File "/usr/local/lib/python3.10/dist-packages/lttnganalyses/cli/cputop.py", line 27, in <module>
    from .command import Command
  File "/usr/local/lib/python3.10/dist-packages/lttnganalyses/cli/command.py", line 33, in <module>
    from . import mi, progressbar, period_parsing
  File "/usr/local/lib/python3.10/dist-packages/lttnganalyses/cli/period_parsing.py", line 24, in <module>
    from ..core import period
  File "/usr/local/lib/python3.10/dist-packages/lttnganalyses/core/period.py", line 23, in <module>
    from . import event as core_event
  File "/usr/local/lib/python3.10/dist-packages/lttnganalyses/core/event.py", line 40, in <module>
    class Event(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
docker@a6e0d2a2abac:~/GE/yocto-build/ansible$ 

```

With previous version:

```
<stdin>:1: DeprecationWarning: Using or importing the ABCs
  from 'collections' instead of from 'collections.abc' is deprecated
  since Python 3.3, and in 3.10 it will stop working
```
